import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
   title: "The North Hub",
   description: "Generated by create next app",
};

export const fontSans = FontSans({
   subsets: ["latin"],
   variable: "--font-sans",
});

export default function RootLayout({ children }: { children: ReactNode }) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body
            className={cn(
               "min-h-screen bg-white font-sans antialiased",
               fontSans.variable,
            )}
         >
            {children}
         </body>
      </html>
   );
}
